DROP TABLE IF EXISTS `0_strikeout`;
CREATE TABLE IF NOT EXISTS `0_strikeout` (
    `so_id` int(11) NOT NULL AUTO_INCREMENT,
    `so_name` VARCHAR(30) DEFAULT NULL,
    `so_method` VARCHAR(30) NOT NULL,
    `so_url` tinytext DEFAULT NULL,
    `so_pub` VARCHAR(512) DEFAULT NULL,
    `so_pub_L` VARCHAR(30) DEFAULT NULL,
    `so_pri` VARCHAR(512) DEFAULT NULL,
    `so_pri_L` VARCHAR(30) DEFAULT NULL,
    `so_percent` double NOT NULL DEFAULT '0',
    `so_discount` double NOT NULL DEFAULT '0',
    `so_custom_1` tinytext DEFAULT NULL,
    `so_custom_1L` VARCHAR(30) DEFAULT NULL,
    `so_custom_2` tinytext DEFAULT NULL,
    `so_custom_2L` VARCHAR(30) DEFAULT NULL,
    `so_custom_3` tinytext DEFAULT NULL,
    `so_custom_3L` VARCHAR(30) DEFAULT NULL,
    `so_custom_4` tinytext DEFAULT NULL,
    `so_custom_4L` VARCHAR(30) DEFAULT NULL,
    `so_user` smallint DEFAULT NULL,
    `so_is_inv` tinyint(1) NOT NULL DEFAULT '0',
    `so_bank` VARCHAR(20) DEFAULT NULL,
    `so_debit` VARCHAR(15) DEFAULT NULL,
    `so_credit` VARCHAR(15) DEFAULT NULL,
    `so_fee` VARCHAR(15) DEFAULT NULL,
    `so_option` VARCHAR(30) DEFAULT NULL,
    `so_inactive` tinyint(1) NOT NULL DEFAULT '0',
    `so_hook_inactive` tinyint(1) NOT NULL DEFAULT '0',
    PRIMARY KEY (`so_id`),
    UNIQUE KEY `so_method` (`so_method`)
) ENGINE=InnoDB;

INSERT INTO `0_strikeout` VALUES 
('1', 'StrikeOut', 'strikeout', 'N/A', 
  NULL, 'N/A', 
  NULL, 'N/A', 
  '0', '0', 
  'America/Los_Angeles', 'Timezone', 
  '/tmp', 'Tmp Dir', 
  'https://strikeoutpay.com', 'Action URL', 
  NULL, 'N/A', 
  NULL, 
  '0', NULL,
  NULL, NULL, NULL, 
  NULL,
  '0', '0');

INSERT INTO `0_strikeout` VALUES 
('2', 'Strike', 'strike', 'N/A', 
  NULL, 'API Key', 
  NULL, 'Secret', 
  '0', '0', 
  NULL, 'N/A', 
  NULL, 'N/A', 
  NULL, 'N/A', 
  NULL, 'N/A', 
  NULL, 
  '0', NULL,
  NULL, NULL, NULL,
  'Bank Deposit',
  '1', '1');

INSERT INTO `0_strikeout` VALUES 
('3', 'LNbits', 'lnbits', 'https://ln.strikeoutpay.com', 
  '', 'Invoice/read key', 
  NULL, 'N/A', 
  '0', '0', 
  NULL, 'Webhook URL', 
  NULL, 'Bits (Bool Def Sats)', 
  NULL, 'N/A', 
  NULL, 'N/A', 
  NULL, 
  '0', NULL,
  NULL, NULL, NULL,
  'Bank Deposit',
  '1', '1');

INSERT INTO `0_strikeout` VALUES 
('4', 'PayPal', 'paypal', 'https://api-m.paypal.com', 
  '', 'Client ID', 
  NULL, 'Secret Key', 
  '0', '0', 
  NULL, 'Webhook ID', 
  NULL, 'SDK Options', 
  NULL, 'N/A', 
  NULL, 'N/A', 
  NULL, 
  '0', NULL,
  NULL, NULL, NULL,
  'Bank Deposit',
  '1', '1');

INSERT INTO `0_strikeout` VALUES 
('5', 'Stripe', 'stripe', '', 
  NULL, 'Public Key', 
  NULL, 'Secret Key', 
  '0', '0', 
  NULL, 'N/A', 
  NULL, 'N/A', 
  NULL, 'N/A', 
  NULL, 'N/A', 
  NULL, 
  '0', NULL,
  NULL, NULL, NULL,
  'Bank Deposit',
  '1', '1');
