<?php
/**********************************************************************
    Released under the terms of the GNU General Public License, GPL, 
    as published by the Free Software Foundation, either version 3 
    of the License, or (at your option) any later version.
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
    See the License here <http://www.gnu.org/licenses/gpl-3.0.html>.

    ================================================================
    Front Additional Fields
    ================================================================
    
***********************************************************************/
include_once($path_to_root . "/modules/strikeout/inc/db/strikeout_db.inc");
include_once($path_to_root . "/modules/strikeout/inc/ui/strikeout_ui.inc");
include_once($path_to_root . "/modules/strikeout/inc/hooks/so_pay_methods.inc");
